"""Create signs table

Revision ID: 4b345e94c8a4
Revises: e267964a68a9
Create Date: 2026-07-31 11:31:29.925524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b345e94c8a4'
down_revision = 'e267964a68a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=150), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signs')
    # ### end Alembic commands ###
